# Generated by Django 3.2.16 on 2023-03-23 09:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0002_alter_hesap_resim'),
    ]

    operations = [
        migrations.AddField(
            model_name='hesap',
            name='takipci',
            field=models.ManyToManyField(related_name='takipci', to=settings.AUTH_USER_MODEL),
        ),
    ]
